# Generated by Django 2.0.5 on 2018-06-18 08:33

from django.db import migrations, models
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    replaces = [
        ('django_q', '0001_initial'),
        ('django_q', '0002_auto_20150630_1624'),
        ('django_q', '0003_auto_20150708_1326'),
        ('django_q', '0004_auto_20150710_1043'),
        ('django_q', '0005_auto_20150718_1506'),
        ('django_q', '0006_auto_20150805_1817'),
        ('django_q', '0007_ormq'),
        ('django_q', '0008_auto_20160224_1026'),
        ('django_q', '0009_auto_20171009_0915')
    ]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrmQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('lock', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Queued tasks',
                'verbose_name': 'Queued task',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('func',
                 models.CharField(help_text='e.g. module.tasks.function',
                                  max_length=256)),
                ('hook', models.CharField(blank=True,
                                          help_text='e.g. '
                                                    'module.tasks.result_function',
                                          max_length=256, null=True)),
                ('args',
                 models.TextField(blank=True, help_text="e.g. 1, 2, 'John'",
                                  null=True)),
                ('kwargs', models.TextField(blank=True,
                                            help_text="e.g. x=1, y=2, "
                                                      "name='John'",
                                            null=True)),
                ('schedule_type', models.CharField(
                    choices=[('O', 'Once'), ('I', 'Minutes'), ('H', 'Hourly'),
                             ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'),
                             ('Q', 'Quarterly'), ('Y', 'Yearly')], default='O',
                    max_length=1, verbose_name='Schedule Type')),
                ('minutes', models.PositiveSmallIntegerField(blank=True,
                                                             help_text='Number of minutes for the Minutes type',
                                                             null=True)),
                ('repeats', models.IntegerField(default=-1,
                                                help_text='n = n times, '
                                                          '-1 = forever',
                                                verbose_name='Repeats')),
                ('next_run',
                 models.DateTimeField(default=django.utils.timezone.now,
                                      null=True, verbose_name='Next Run')),
                ('task',
                 models.CharField(editable=False, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Scheduled tasks',
                'verbose_name': 'Scheduled task',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=32,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=100)),
                ('func', models.CharField(max_length=256)),
                ('hook', models.CharField(max_length=256, null=True)),
                ('args', picklefield.fields.PickledObjectField(editable=False,
                                                               null=True)),
                ('kwargs',
                 picklefield.fields.PickledObjectField(editable=False,
                                                       null=True)),
                ('result',
                 picklefield.fields.PickledObjectField(editable=False,
                                                       null=True)),
                ('group',
                 models.CharField(editable=False, max_length=100, null=True)),
                ('started', models.DateTimeField(editable=False)),
                ('stopped', models.DateTimeField(editable=False)),
                ('success', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ['-stopped'],
            },
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Failed tasks',
                'verbose_name': 'Failed task',
                'indexes': [],
                'proxy': True,
                'ordering': ['-stopped'],
            },
            bases=('django_q.task',),
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Successful tasks',
                'verbose_name': 'Successful task',
                'indexes': [],
                'proxy': True,
                'ordering': ['-stopped'],
            },
            bases=('django_q.task',),
        ),
    ]
