# Generated by Django 2.1.2 on 2018-12-07 09:29

from django.db import migrations
import django_q.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0001_squashed_0009_auto_20171009_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='args_boxed',
            field=django_q.models.BoxedPickledObjectField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='kwargs_boxed',
            field=django_q.models.BoxedPickledObjectField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='result_boxed',
            field=django_q.models.BoxedPickledObjectField(editable=False, null=True),
        ),
    ]
