# Generated by Django 2.1.2 on 2018-12-07 09:32

from django.db import migrations


def move_to_boxed(apps, schema_editor):
    Task = apps.get_model('django_q.Task')

    for task in Task.objects.all():
        task.args_boxed = task.args
        task.kwargs_boxed = task.kwargs
        task.result_boxed = task.result
        task.save()


def move_from_boxed(apps, schema_editor):
    Task = apps.get_model('django_q.Task')

    for task in Task.objects.all():
        task.args = task.args_boxed
        task.kwargs = task.kwargs_boxed
        task.result = task.result_boxed
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0002_add_boxed'),
    ]

    operations = [
        migrations.RunPython(move_to_boxed, move_from_boxed),
    ]
