# Generated by Django 2.1.2 on 2018-12-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0003_move_to_boxed'),
    ]

    operations = [
        migrations.RemoveField('task', 'args'),
        migrations.RemoveField('task', 'kwargs'),
        migrations.RemoveField('task', 'result'),
        migrations.RenameField('task', 'args_boxed', 'args'),
        migrations.RenameField('task', 'kwargs_boxed', 'kwargs'),
        migrations.RenameField('task', 'result_boxed', 'result'),
    ]
